host = "0.0.0.0:9090"
env = "prod"
v8_maxcount = 30
v8_lifetime = 3600
client_path = "jsproj"
static_url_path = "/static"
is_api_delegate = false
internal_api_ip = "127.0.0.1"
internal_api_port = 80
template_name = "ssr.prod.html"
client_cookie = "goblogssr_id"
redirect_onerror = "/error/404"
ssr_ctx = ["User-Agent","X-Forwarded-For"]
template_vars = [{key = "State", type = "js"},
    {key = "OgImage", type = "html"}]

[Log]
debug=false
filenum=20
filesize=256
filename="run"
level="INFO"
dir="/data/log/goblogssr_logs"
